// Generated by scripts/generate_sparse_mel.py; do not edit.
// Source: published v2 coefficients/mel_q16.bin SHA-256:
// f6476ace9b81e9b5f19da0cec2e10293ed2cc3387827d683862685f93b1c3dfc
// Unsigned F16 coefficients; ascending contiguous support per band.
module fixed_mel_descriptor (
    input  logic [4:0] i_band,
    output logic [8:0] o_start_bin,
    output logic [8:0] o_length,
    output logic [8:0] o_offset
);
    always_comb begin
        o_start_bin = 9'd0;
        o_length = 9'd0;
        o_offset = 9'd0;
        case (i_band)
            5'd0: begin
                o_start_bin = 9'd1;
                o_length = 9'd3;
                o_offset = 9'd0;
            end
            5'd1: begin
                o_start_bin = 9'd3;
                o_length = 9'd4;
                o_offset = 9'd3;
            end
            5'd2: begin
                o_start_bin = 9'd5;
                o_length = 9'd5;
                o_offset = 9'd7;
            end
            5'd3: begin
                o_start_bin = 9'd8;
                o_length = 9'd5;
                o_offset = 9'd12;
            end
            5'd4: begin
                o_start_bin = 9'd11;
                o_length = 9'd5;
                o_offset = 9'd17;
            end
            5'd5: begin
                o_start_bin = 9'd14;
                o_length = 9'd6;
                o_offset = 9'd22;
            end
            5'd6: begin
                o_start_bin = 9'd17;
                o_length = 9'd7;
                o_offset = 9'd28;
            end
            5'd7: begin
                o_start_bin = 9'd21;
                o_length = 9'd8;
                o_offset = 9'd35;
            end
            5'd8: begin
                o_start_bin = 9'd25;
                o_length = 9'd9;
                o_offset = 9'd43;
            end
            5'd9: begin
                o_start_bin = 9'd30;
                o_length = 9'd10;
                o_offset = 9'd52;
            end
            5'd10: begin
                o_start_bin = 9'd35;
                o_length = 9'd11;
                o_offset = 9'd62;
            end
            5'd11: begin
                o_start_bin = 9'd41;
                o_length = 9'd12;
                o_offset = 9'd73;
            end
            5'd12: begin
                o_start_bin = 9'd47;
                o_length = 9'd13;
                o_offset = 9'd85;
            end
            5'd13: begin
                o_start_bin = 9'd54;
                o_length = 9'd14;
                o_offset = 9'd98;
            end
            5'd14: begin
                o_start_bin = 9'd61;
                o_length = 9'd16;
                o_offset = 9'd112;
            end
            5'd15: begin
                o_start_bin = 9'd69;
                o_length = 9'd18;
                o_offset = 9'd128;
            end
            5'd16: begin
                o_start_bin = 9'd78;
                o_length = 9'd19;
                o_offset = 9'd146;
            end
            5'd17: begin
                o_start_bin = 9'd88;
                o_length = 9'd21;
                o_offset = 9'd165;
            end
            5'd18: begin
                o_start_bin = 9'd98;
                o_length = 9'd24;
                o_offset = 9'd186;
            end
            5'd19: begin
                o_start_bin = 9'd110;
                o_length = 9'd26;
                o_offset = 9'd210;
            end
            5'd20: begin
                o_start_bin = 9'd123;
                o_length = 9'd29;
                o_offset = 9'd236;
            end
            5'd21: begin
                o_start_bin = 9'd137;
                o_length = 9'd32;
                o_offset = 9'd265;
            end
            5'd22: begin
                o_start_bin = 9'd153;
                o_length = 9'd35;
                o_offset = 9'd297;
            end
            5'd23: begin
                o_start_bin = 9'd170;
                o_length = 9'd39;
                o_offset = 9'd332;
            end
            5'd24: begin
                o_start_bin = 9'd189;
                o_length = 9'd42;
                o_offset = 9'd371;
            end
            5'd25: begin
                o_start_bin = 9'd210;
                o_length = 9'd46;
                o_offset = 9'd413;
            end
            default: begin
                o_start_bin = 9'd0;
                o_length = 9'd0;
                o_offset = 9'd0;
            end
        endcase
    end
endmodule
