"""Deterministic RTL constants from the same offline integer coefficients as v2."""
from pathlib import Path
import json
import sys
from fractions import Fraction
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT))
from scripts.run_fixed_full_model import generate_coefficients

def main():
    coeff,_=generate_coefficients()
    out=ROOT / "hardware/fixed/log_dct"
    out.mkdir(parents=True,exist_ok=True)
    floor=Fraction(1e-12)
    thresholds=[(floor*(1<<(43+2*s))).__ceil__() for s in range(-2,25)]
    assert thresholds==[(Fraction(1,10**12)*(1<<(43+2*s))).__ceil__() for s in range(-2,25)]
    lines=["// Generated by scripts/generate_fixed_integer_rtl.py. Binary64 1e-12 floor.","module mfcc_fixed_floor_threshold(input logic signed [5:0] i_bfp_s,output logic [59:0] o_threshold);","    always_comb begin","        o_threshold=60'd0;","        case(i_bfp_s)"]
    for s,t in zip(range(-2,25),thresholds):
        key=f"-6'sd{-s}" if s<0 else f"6'sd{s}"
        lines.append(f"            {key}: o_threshold=60'd{t};")
    lines += ["            default: o_threshold=60'd0;","        endcase","    end","endmodule",""]
    (out / "mfcc_fixed_floor_threshold.sv").write_text("\n".join(lines),encoding="utf-8")
    lines=["// Generated from frozen float64 orthonormal DCT, RNE to F30.","module mfcc_fixed_dct_coefficient(input logic [3:0] i_coef,input logic [4:0] i_sample,output logic signed [30:0] o_coefficient);","    always_comb begin","        o_coefficient=31'sd0;","        case({i_coef,i_sample})"]
    for c,row in enumerate(coeff["dct_q30"]):
        for m,value in enumerate(row):
            literal=f"-31'sd{-value}" if value<0 else f"31'sd{value}"
            lines.append(f"            9'd{c*32+m}: o_coefficient={literal};")
    lines += ["            default: o_coefficient=31'sd0;","        endcase","    end","endmodule",""]
    (out / "mfcc_fixed_dct_coefficient.sv").write_text("\n".join(lines),encoding="utf-8")
    out=ROOT / "hardware/fixed/frontend"
    out.mkdir(parents=True,exist_ok=True)
    lines=["// Generated from frozen symmetric Hamming, RNE to unsigned31/F30.","module mfcc_fixed_window_coefficient(input logic [8:0] i_index,output logic [30:0] o_coefficient);","    always_comb begin","        o_coefficient=31'd0;","        case(i_index)"]
    for i,value in enumerate(coeff["window_q30"]):
        lines.append(f"            9'd{i}: o_coefficient=31'd{value};")
    lines += ["            default: o_coefficient=31'd0;","        endcase","    end","endmodule",""]
    (out / "mfcc_fixed_window_coefficient.sv").write_text("\n".join(lines),encoding="utf-8")
    print(json.dumps({"thresholds":thresholds,"generated":"frontend/window, log/floor, DCT coefficients"}))

if __name__=="__main__":main()
