// Generated by scripts/generate_fixed_integer_rtl.py. Binary64 1e-12 floor.
module mfcc_fixed_floor_threshold(input logic signed [5:0] i_bfp_s,output logic [59:0] o_threshold);
    always_comb begin
        o_threshold=60'd0;
        case(i_bfp_s)
            -6'sd2: o_threshold=60'd1;
            -6'sd1: o_threshold=60'd3;
            6'sd0: o_threshold=60'd9;
            6'sd1: o_threshold=60'd36;
            6'sd2: o_threshold=60'd141;
            6'sd3: o_threshold=60'd563;
            6'sd4: o_threshold=60'd2252;
            6'sd5: o_threshold=60'd9008;
            6'sd6: o_threshold=60'd36029;
            6'sd7: o_threshold=60'd144116;
            6'sd8: o_threshold=60'd576461;
            6'sd9: o_threshold=60'd2305844;
            6'sd10: o_threshold=60'd9223373;
            6'sd11: o_threshold=60'd36893489;
            6'sd12: o_threshold=60'd147573953;
            6'sd13: o_threshold=60'd590295811;
            6'sd14: o_threshold=60'd2361183242;
            6'sd15: o_threshold=60'd9444732966;
            6'sd16: o_threshold=60'd37778931863;
            6'sd17: o_threshold=60'd151115727452;
            6'sd18: o_threshold=60'd604462909808;
            6'sd19: o_threshold=60'd2417851639230;
            6'sd20: o_threshold=60'd9671406556918;
            6'sd21: o_threshold=60'd38685626227669;
            6'sd22: o_threshold=60'd154742504910673;
            6'sd23: o_threshold=60'd618970019642691;
            6'sd24: o_threshold=60'd2475880078570761;
            default: o_threshold=60'd0;
        endcase
    end
endmodule
